### ISSUE TITLE
personalizzazione nel footer "Template by ..... per @opendatasicilia"

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/ods-mkdocs-material#1]
Nel footer si legge:
**Template by @gbvitrano per @opendatasisilia** 

Dovremmo rendere il progetto MKDocs-start di ODS quanto più asciutto possibile, cioè libero da questi tipi di personalizzazioni che prevedono editing nel file `main.html` ... cioè operazioni non alla portata di tutti.

Propongo di eliminarlo.
E' solo una mia personale opinione, chiaramente.

Il progetto MKDocs-start di ODS sarà con i  nomi di chi ci lavora, @gbvitrano in testa!!!

**Comment by gbvitrano** [comment]
Ho modificato il template, ho eliminato tutte le varie personalizzazioni che avrebbero avuto bisogno di ulteriore editing da parte dell'utente finale.

Codice eliminato:
-  Eliminato logo, favicon e css extra,  ogni piccola variazione di dimensione e colore del testo comporta editing nel css e crea difficoltà;
-  Eliminata personalizzazione dei meta tag comprese le social card, richiedono intervento manuale nel file main.html, cuore del del vecchio template, troppo delicato per utenti non esperti;
-  Popup cookies #2  eliminato perché anche eliminando logo e nome del sito necessita di intervento manuale per inserire il link della pagina che punta alla privacy. A pagamento [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=cookies#cookie-consent) risolve il problema;
-  Non avendo il popup dei cookies ho eliminato i Google fonts, che google usa per il tracciamento;
- Eliminata parte di codice riservata a [Google Analytics](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=cookies#google-analytics), chi lo desidera la installa in proprio seguendo la semplice guida;
- Eliminata bara di avanzamento pagina, necessita intervento nello script o nel main.html per gestire colore, dimensione e posizione;
- Eliminata plugin di stampa, il template necessita configurazione manuale;
- Eliminate le icone social non essenziali, nella rimanente parte l'utente deve inserire i link ai suoi social ed eventualmente aggiungerne altre di suo interesse;

La plugin RSS è attiva, una volta installata e messo il link visibile nel sito, non ha bisogno di intervento.

L'istallazione delle gh-page è sempre in automatico, basta ricordarsi di attivarle nel repo.

Non è previsto il file di configurazione per RDT, vista la compilazione in loco RDT è superfluo, un utente esperto saprà cosa fare per attivarla. Uno poco esperto non sa nemmeno cosa sia RDT e non ne sente il bisogno. :-)

Visto che ho eliminato Google Analytics e Google fonts andrebbe modificato anche il file della privacy o meglio si potrebbe anche rimuovere del tutto, ma visto che il tema lo prendiamo dal repo di squidfunk meglio lasciarlo non si sa mai :-)

Credo di aver eliminato ogni possibile personalizzazione  e reso tutto il più semplice possibile, colpa mia che per passione mi faccio prendere la mano.  :-)  :-)  :-)

Adesso il template è asciutto e pronto all'uso anche per l'utente meno esperto.

**Comment by cirospat** [comment]
Grazie @gbvitrano  per il lavoro.

Il pop-up sui cookies è obbligatorio nei siti web, per legge. 
Penso che bisogna assicurarlo nella struttura del repo, dando indicazioni operative precise su come attivarlo.
Che ne pensi?

**Comment by gbvitrano** [comment]
In molti siti realizzati mkdocs matirial che ho visitato, il popup per i cookies non l'ho mai visto, infondo se non usi alcun tipo di tracciamento come in questo caso, per cosa va avvisato l'utente? :-) 

Se l'utente utilizza tools per il tracciamento  vuol dire che è un utente smanettone, quindi saprà da se come fare per implementare i cookies, in caso contrario con una donazione ci si affida a   [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=cookies#cookie-consent) e si risolve il problema :-)

**Comment by cirospat** [comment]
@gbvitrano non vorrei sbagliare (e forse sbaglio),
ma c'è una norma che stabilisce la pubblicazione/avviso di questa **informativa** che informa il visitatore su cosa fa il sito nei confronti dello stesso visitatore. Se non fa niente, allora nell'informativa verrà scritto che non fa niente, ma l'**informativa** da quello che ho capito è un obbligo di legge.

**Comment by gbvitrano** [comment]
Io non ho soluzioni che non comportano editing dello script o css del popup, perchè qualsiasi cosa trovi in merito, riadattata alle proprie esigenze.
Mkdocs Matirial ha una soluzione nativa che risolve il problema

**Comment by cirospat** [comment]
qual è questa soluzione nativa di MKdocs?

**Comment by gbvitrano** [comment]
# [Material for MkDocs cookies](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=cookies#cookie-consent)

**Comment by cirospat** [comment]
grazie Gianni
ho letto e continuo a studiare



Il giorno dom 25 lug 2021 alle ore 18:56 Giovan Battista Vitrano <
***@***.***> ha scritto:

**Comment by aborruso** [comment]
> Il pop-up sui cookies è obbligatorio nei siti web, per legge.

È obbligatorio se si usano in qualche modo. 

Io rilascerei un template in cui non se ne fa uso, e senza odiose tendine che appaiono.

**Comment by gbvitrano** [comment]
visto che abbiamo asciugato il sito :-)  :-)  :-) anche questa la chiudo

**Comment by cirospat** [comment]
ho riaperto l'issue solo per comunicare una cosa che penso, @gbvitrano @aborruso @pigreco 

Le personalizzazioni nei setting (overrides - stylesheet) si possono fare secondo me. 
Le possiamo documentare (abbiamo fatto questo per fare apparire questo nella pagina web...).
Personalizzazioni che gli utenti meno esperti comunque non dovrebbero toccare/settare nei loro progetti individuali. 
Gli utenti si dovrebbero concentrare solo nella pagina `.yml` e nei documenti nelle pagine `.md`.

Le personalizzazioni rendono la pagina web più gradevole rispetto al tema basic di MKDocs. E perchè non regalare un modello gradevole?!
Però non diamo agli utenti l'onere di andare nei file di overrides e stylesheet per modificare codice. Questo voglio dire.
L'informativa cookies-privacy - ad esempio - si può fare generale (senza scrivere Questo progetto "opendatasicilia" .....) ed essendo generale tutti la possono usare senza modificare.

La generazione del progetto in formato PDF è uno strumento utile negli ambienti delle pubbliche amministrazioni. Dare questo strumento nel progetto è importante, secondo me. Dargli un strumento nuovo e nel frattempo non li fare sentire a disagio senza un PDF (transizione culturale).

Sono sicuro che sin dall'inizio mi sono spiegato non chiaramente in quello che volevo fare per creare un modello di MKDocs gradevole esteticamente e facilmente riusabile da utenti non esperti.

Sarebbe utile fare una mezzoretta di riunione per questo argomento, secondo me.
Grazie per l'ascolto

**Comment by gbvitrano** [comment]
ne asciutto...ne molto bagnato, umido :-) :-) :-) 
Mi sono convinto ed ora cambi idea :-)

Per fare template accessibile a tutti meno cose mettiamo meglio è, perché poi si inizia... il colore non colora, il link non linka.... ogni utente avrà esigenze e gusti diversi,  ho scelto per le palette il bianco ed il nero per essere più neutro possibile. 
Poi liberi di inserire tutto quello che vi piace :-) 
Per la privacy, se non si usano traccianti come Ads, google fonts, google analytics e pulsati di condivisione social, non serve. L'utente che li usa avrà l'onere di inserirlo, (questo magari lo scriviamo espressamente nella guida).
Per la stampa in pdf i come tutti i plugin hanno bisogno di configurazione del template di stampa. 
I moderni browser rendono superfluo tali plugin.
tasto destro del mouse sulla pagina e magia... si apre la tendina con due comandi molto utili :-) e il pdf è servito anche per i meno smanettoni :-)
![image](https://user-images.githubusercontent.com/20488693/127242691-9953da9a-0863-4ed4-a4da-5a144ce8d051.png)
