### ISSUE TITLE
avviso cookies/privacy personalizzato alla prima visita del sito

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/ods-mkdocs-material#2]
![image](https://user-images.githubusercontent.com/3757525/126859855-043713ba-784b-404b-a1e6-2f1555dc00f0.png)

quando si apre per la prima volta la home del progetto si vede il logo di ODS e il testo che comincia: Questo sito, OpenDataSicilia utilizza i cookie, .......

E' una personalizzazione che prevede l'editing in un file specifico.
Immagino il progetto **MKDocs-start** di ODS il più asciutto possibile in termini di personalizzazioni che poi ogni volta devono essere effettuate nei vari progetti di riuso del **MKDocs-start** e non sopo operazioni alla portata di tutti.

Propongo di eliminare questa personalizzazione (immagine + testo in cui si menziona opendatasicilia).
Opinione personale chiaramente.

**Comment by aborruso** [comment]
Io rimuoverei tutto questo. Un template base a mio avviso non lo deve avere, perché il sito di base non userà i cookie.

**Comment by gbvitrano** [comment]
già rimosso tutto il superfluo :-)

**Comment by aborruso** [comment]
> già rimosso tutto il superfluo :-)

ok, qualcuno chiuda la issue allora
