### ISSUE TITLE
Creare pagina con le feature/caratteristiche abilitate in questa "nostra" versione

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ods-mkdocs-material#33]

**Comment by aborruso** [comment]
Ciao @gbvitrano ho creato la pagina che dei segnaposto: https://opendatasicilia.github.io/ods-mkdocs-material/Riferimenti/caratteristiche/

Voglio raccogliere le cose che abbiamo attivato in questa release, le cose che ci sembra che siano utili e di base da attivare.

Per ora sono sole dei titoli. Non ci rimane che:

- aggiungere le altre cose che abbiamo attivato/attiveremo;
- aggiungere oltre al titolo una descrizione

**Comment by gbvitrano** [comment]
- Allineamento dell'immagine
