### ISSUE TITLE
Commentare tutte le estensioni che non sono utilizzate o si pensa di non utilizzare

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ods-mkdocs-material#39]
Caro @gbvitrano,
questi problemi di @cirospat che ho risolto facendo cose strane, in realtà era dovuta a [un'estensione che non usiamo](https://github.com/opendatasicilia/ods-mkdocs-material/commit/0c8aa049634cb6d52c623d9c9916d21d0051aa5a), ma che rendeva più difficile il tutto.

Puoi per favore commentare le estensioni che hai inserito, ma non usiamo?

Grazie

**Comment by gbvitrano** [comment]
estensioni disattivate
