### ISSUE TITLE
Immagini da mobile

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods-mkdocs-material#45]
Buonasera a tutti, visitando questa pagina https://opendatasicilia.github.io/ods-mkdocs-material/Ricette/ da mobile, le immagini "rompono' il layout. Forse andrebbe impostato il width 100% (ma non si esattamente dove farlo)

Allego screenshot: Samsung S8, Chrome browser
![Screenshot_20211128-173506_Chrome](https://user-images.githubusercontent.com/77018886/143777349-84707b8c-5404-4e79-a18d-a9b0067bc523.jpg)

**Comment by aborruso** [comment]
Ciao @dennisangemi io da mobile lo vedo senza nulla rotto.

O non ho capito nulla?

![image](https://user-images.githubusercontent.com/30607/143777543-b8479c5f-5100-4167-ab07-527ec7e17b8b.png)

**Comment by dennisangemi** [comment]
> O non ho capito nulla?

@aborruso nonostante io mi sia spiegato malissimo tu hai capito. Forse a questo punto è un problema solo mio

**Comment by aborruso** [comment]
Ciao @dennisangemi ,
facendo vari test, mi sembra sempre leggibile.

Due cose:
- provi in navigazione anonima?
- ti installi firefox sul cellulare e mi dici come va?

![image](https://user-images.githubusercontent.com/30607/143777873-5a1b6ac0-9dc0-42fa-9504-3cb56f67ac24.png)

**Comment by dennisangemi** [comment]
> * provi in navigazione anonima?
Navigazione anonima con chrome presenta lo stesso problema

> * ti installi firefox sul cellulare e mi dici come va?
Tutto perfetto.

**Comment by aborruso** [comment]
> Navigazione anonima con chrome presenta lo stesso problema

A me da chrome non dà nessun problema :(

**Comment by dennisangemi** [comment]
Avendo appurato che è il mio telefono a fare le bizze chiudi. Grazie @aborruso

**Comment by gbvitrano** [comment]
Dennis  perché usi da mobile la navigazione desktop? Da mobile non noto
nulla di strano

Giovan Battista Vitrano - mobile - @gbvitrano

Il dom 28 nov 2021, 19:35 Dennis Angemi ***@***.***> ha
scritto:
