### ISSUE TITLE
code annotation

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/ods-mkdocs-material#46]
vorrei capire quali istruzioni bisogna dare e in quali file, oltre a quanto scritto qui:
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations

lo chiedo perchè in un repo = https://github.com/UO-TransizioneDigitaleComunePalermo/mappatura-procedimenti-amministrativi
e relativo sito = https://uo-transizionedigitalecomunepalermo.github.io/mappatura-procedimenti-amministrativi/note/#code-annotation-annotazioni-nel-blocco-codice

non visualizzo il pop up del `code annotation`

**Comment by aborruso** [comment]
@cirospat non ho modificato nulla, ho soltanto forzato il building (che avviene automaticamente quando modifichi una pagina).
