### ISSUE TITLE
run: pip install mkdocs-jupyter su (gh-deploy.yml) abilita funzioni e ne disabilita altre

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/ods-mkdocs-material#47]
credo di aver capito una cosa sul file `gh-deploy.yml`

**`- run: pip install mkdocs-jupyter `**       
            
se inserito: 

- abilita i "content tabs" 
- e disabilita le "code annotation"

viceversa se non inserito:

- disabilita i "content tabs" 
- e abilita le "code annotation"

credo sia un problema, in quanto se si vogliono attive ambedue le funzioni come si fa?

**Comment by cirospat** [comment]
Jupiter mi abilita i content tabs
![image](https://user-images.githubusercontent.com/3757525/143873332-83fc32a9-b834-4e15-a2c5-964182e9da6f.png)

[qui](https://uo-transizionedigitalecomunepalermo.github.io/mappatura-procedimenti-amministrativi/contenuti/fasi-operative/#scheda-delle-fasi-operative-del-procedimento-amministrativo) e altrove. E' comodo.

**Comment by cirospat** [comment]
secondo me si dovrebbe documentare ogni plugin.
Ma bisogna sapere cosa fa ogni singolo plugin.

**Comment by aborruso** [comment]
@cirospat ma dove trovo che per i [content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/?h=cont) ci vuole `mkdocs-jupyter`?

**Comment by aborruso** [comment]
@cirospat ecco content tab applicato, senza `mkdocs-jupyter`:

https://opendatasicilia.github.io/ods-mkdocs-material/Riferimenti/formattazione/#grafici

**Comment by aborruso** [comment]
Scusa, ho sbagliato URL: https://opendatasicilia.github.io/ods-mkdocs-material/Riferimenti/formattazione/#contenuti-divisi-in-tab

**Comment by cirospat** [comment]
> URL: https://opendatasicilia.github.io/ods-mkdocs-material/Riferimenti/formattazione/#contenuti-divisi-in-tab

grazie  @aborruso 

il codice
```
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
```
già si trovava nel `mkdocs.yaml` del repo al quale sto lavorando.

Il problema è che se tolgo dal `gh-deploy.yml` il plugin `mkdocs-jupyter`, non visualizzo più la funzione "**Contenuti divisi in tab**"

E mi sono bloccato.

**Comment by aborruso** [comment]
Come vedi jupyter non serve, nel senso che qui come vedi funziona tutto.

Prendi spunto da questo file che è sempre più puliticchio (e che ridurremo ancora): https://github.com/opendatasicilia/ods-mkdocs-material/blob/main/.github/workflows/gh-deploy.yml

**Comment by cirospat** [comment]
allora ho pulito tutto nel `gh-deploy.yml`:
https://github.com/UO-TransizioneDigitaleComunePalermo/mappatura-procedimenti-amministrativi/blob/main/.github/workflows/gh-deploy.yml

ma se levo `mkdocs-jupyter` non mi fa visualizzare le content tabs
![image](https://user-images.githubusercontent.com/3757525/143898021-fd99305b-d71b-476c-8524-daadc14f7c12.png)

poi per il resto il `mkdocs.yaml`  è uguale a quello di ods-mkdocs-material

Sono ad un punto morto

**Comment by aborruso** [comment]
@cirospat mi puoi lasciare una pagina "prova", che non metti nei menu?

Così me la guardo

**Comment by cirospat** [comment]
https://uo-transizionedigitalecomunepalermo.github.io/mappatura-procedimenti-amministrativi/note

**Comment by aborruso** [comment]
@cirospat problema risolto 
![image](https://user-images.githubusercontent.com/30607/143905085-da1d342f-aa4b-4613-9c24-ba2248b9b8ab.png)


https://github.com/UO-TransizioneDigitaleComunePalermo/mappatura-procedimenti-amministrativi/issues/15
