### ISSUE TITLE
disattivato plugin "Disqus" da MKDocs-material. Come si inserisce manualmente nel progetto?

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/ods-mkdocs-material#50]
Nella versione 8 di MKDocs-material è stato disattivato `Disqus`.

Nella piattaforma di Disqus ho il codice per inserire il sistema di commenti. Il codice è il seguente:
```
<div id="disqus_thread"></div>
<script>
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://mkdocs.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
```

Dove (in quale file) e come (in che esatta posizione del file)  inserisco il codice nel progetto MKDocs-material così da farlo visionare in tutte le pagine web?
Grazie in anticipo

**Comment by cirospat** [comment]
la risposta è sempre nel maestro:
https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/

si crea un file `content.html` nella cartella `override/partial`

**Comment by aborruso** [comment]
Ciro quindi hai risolto?

**Comment by cirospat** [comment]
si ho risolto e chiudo issue
