### ISSUE TITLE
RSS non funziona?

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods-mkdocs-material#59]
Ciao @aborruso & co, ho provato a fare click sull'icona dell'RSS nel footer di https://opendatasicilia.github.io/ods-mkdocs-material/ ma vengo dirottato alla pagina che https://opendatasicilia.github.io/feed_rss_created.xml restituisce `Site not found`

![image](https://user-images.githubusercontent.com/77018886/230063888-c6287b66-0bcb-4e90-a166-c09cf9a11b69.png)

Vedo che installiamo 

https://github.com/opendatasicilia/ods-mkdocs-material/blob/03d30529dd46131d512f665b2c9dff7f86bb0fa9/requirements.txt#L8

cc @gbvitrano @cirospat

**Comment by aborruso** [comment]
è un repo su cui non lavoriamo da tempo, e si potrebbe essere rotto qualcosa con l'avanzamento di mkdocs.

Non appena posso ci guardo (o ci guardi anche tu o qualcun altro). 

Sarà cosa da 5 minuti

**Comment by aborruso** [comment]
Solved. Grazie @dennisangemi

**Comment by dennisangemi** [comment]
Grazie  @aborruso, rifletto l'edit in https://github.com/UNICT-DMI/DFA-compiti. thx <3
